export const themes = {
  light: {
    name: 'light',
    colors: {
      '--bg': '#ffffff',
      '--text': '#121212',
      '--text-gray': '#6c7275',
      '--text2': '#377dff',
      '--hover': '#434141',
      
      '--hero-bg': 'linear-gradient(135deg, #ffffff 0%, #3b82f6 25%, #0ea5e9 50%, #94a3b8 75%, #cbd5e1 100%)',
      '--hero-text': '#1e293b',
      '--hero-description': 'rgba(30, 41, 59, 0.9)',
      '--hero-btn-bg': 'linear-gradient(135deg, #1e293b 0%, #334155 100%)',
      '--hero-btn-text': '#ffffff',
      '--hero-btn-hover-bg': 'linear-gradient(135deg, #334155 0%, #475569 100%)',
      '--hero-btn-hover-text': '#ffffff',
      '--hero-overlay': 'rgba(255, 255, 255, 0.1)',
      
      // NavBar - Light Theme
      '--navbar-bg': '#ffffff',
      '--navbar-border': '#e2e8f0',
      '--navbar-text': '#121212',
      '--navbar-text-hover': '#377dff',
      '--navbar-active': '#377dff',
      '--navbar-toggler': '#121212',
      '--navbar-toggler-border': '#d1d5db',
      '--navbar-toggler-bg': '#ffffff',
      '--navbar-toggler-hover-bg': '#f3f4f6',
      '--navbar-toggler-hover-border': '#377dff',
      '--navbar-link-border': 'transparent',
      '--navbar-link-hover-bg': 'rgba(55, 125, 255, 0.1)',
      '--navbar-link-active-bg': 'rgba(55, 125, 255, 0.15)',
      '--navbar-collapse-bg': '#ffffff',
      '--navbar-shadow': '0 2px 8px rgba(18, 18, 18, 0.1)',
      
      // Cards & Components
      '--card-bg': '#ffffff',
      '--card-border': '#e2e8f0',
      '--card-shadow': '0 0.1rem 0.2rem rgba(0, 0, 0, 0.05)',
      
      // Buttons
      '--btn-primary': '#377dff',
      '--btn-primary-hover': '#2563eb',
      '--btn-secondary': '#f3f4f6',
      '--btn-secondary-hover': '#e5e7eb',
      '--btn-text': '#ffffff',
      
      // Add to Cart Button - Light Theme
      '--add-to-cart-bg': '#377dff',
      '--add-to-cart-hover-bg': '#2563eb',
      '--add-to-cart-text': '#ffffff',
      '--add-to-cart-shadow': '0 2px 4px rgba(55, 125, 255, 0.2)',
      '--add-to-cart-shadow-hover': '0 4px 8px rgba(55, 125, 255, 0.3)',
      
      // Forms & Inputs
      '--input-bg': '#ffffff',
      '--input-border': '#d1d5db',
      '--input-focus': '#377dff',
      '--input-text': '#121212',
      
      // Counter & Badges
      '--counter-bg': '#f5f5f5',
      '--counter-text': '#ffffff',
      
      // Secondary Colors
      '--secondary-color': '#38cb89',
      '--secondary-bg': '#f3f5f7',
      
      // Footer - Light Theme
      '--footer-bg': '#f8fafc',
      '--footer-text': '#374151',
      '--footer-link': '#377dff',
      '--footer-link-hover': '#2563eb',
      '--footer-border': '#e5e7eb',
      '--footer-icon': '#6b7280',
      '--footer-icon-hover': '#377dff',
      
      // Cart & Account Pages
      '--page-bg': '#f8fafc',
      '--section-bg': '#ffffff',
      '--border-color': '#e2e8f0',
      '--text-muted': '#6c7275',
      '--text-primary': '#121212',
      '--text-secondary': '#6c7275',
      
      '--product-card-bg': '#ffffff',
      '--product-card-border': '#e2e8f0',
      '--product-card-shadow': '0 2px 8px rgba(0, 0, 0, 0.1)',
      '--product-card-shadow-hover': '0 8px 25px rgba(0, 0, 0, 0.15)',
      '--product-price': '#377dff',
      '--product-price-old': '#6c7275',
      '--product-title': '#121212',
      '--product-description': '#6c7275',
      '--product-image-bg': '#f8fafc',
      
      '--star-filled': '#000000',
      '--star-empty': '#e5e7eb',
      '--star-empty-border': '#d1d5db',
      '--star-size': '16px',
      
      '--icon-color': '#6c7275',
      '--icon-bg': '#ffffff',
      '--icon-hover-bg': '#377dff',
      '--icon-hover-color': '#ffffff',
      '--icon-shadow': '0 2px 4px rgba(0, 0, 0, 0.1)',
      '--icon-shadow-hover': '0 4px 8px rgba(0, 0, 0, 0.15)',
      '--favorite-filled-color': '#e74c3c',
      '--favorite-hover-color': '#c0392b',
      
      '--badge-new-bg': '#38cb89',
      '--badge-discount-bg': '#ff6b6b',
      '--badge-text': '#ffffff',
      
      // Category Cards
      '--category-card-bg': '#ffffff',
      '--category-card-border': '#e2e8f0',
      '--category-title': '#121212',
      '--category-text': '#6c7275',
      '--category-count': '#377dff',
      
      // Tables
      '--table-bg': '#ffffff',
      '--table-border': '#e2e8f0',
      '--table-header-bg': '#f8fafc',
      '--table-row-hover': '#f1f5f9',
      
      // Design System Colors
      '--bg-primary': '#ffffff',
      '--primary-600': '#377dff',
      
      // Modal
      '--modal-bg': '#ffffff',
      '--modal-close-bg': '#ef4444',
      '--modal-close-text': '#ffffff',
      '--modal-close-hover-bg': '#dc2626',

      '--indicator-bg': '#e5e7eb',
      '--indicator-active': '#377dff',
      '--indicator-hover': '#d1d5db',

      // View More Button - Light Theme
      '--view-more-btn-bg': '#377dff',
      '--view-more-btn-text': '#ffffff',
      '--view-more-btn-hover-bg': '#2563eb',
      '--view-more-btn-hover-text': '#ffffff',
      '--view-more-btn-border': '#377dff',
      '--view-more-btn-shadow': '0 4px 12px rgba(55, 125, 255, 0.3)',
      '--view-more-btn-shadow-hover': '0 6px 16px rgba(55, 125, 255, 0.4)',

      // Shop Page Hero - Light Theme
      '--shop-hero-bg': 'linear-gradient(135deg, #0ea5e9 0%, #3b82f6 33%, #94a3b8 66%, #64748b 100%)',
      '--shop-hero-text': '#ffffff',
      '--shop-hero-subtitle': '#ffffff',
      
      // Shop Form Elements - Light Theme
      '--form-label': '#121212',
      '--form-input-bg': '#ffffff',
      '--form-input-border': '#d1d5db',
      '--form-input-text': '#121212',
      '--form-input-placeholder': '#6b7280',
      '--form-input-focus-border': '#377dff',
      '--form-input-focus-shadow': '0 0 0 3px rgba(55, 125, 255, 0.1)',

      // Contact Page - Light Theme
      '--contact-info-bg': '#f8fafc',
      '--contact-info-border': '#e2e8f0',
      '--contact-info-hover-bg': '#f1f5f9',
      '--contact-info-hover-border': '#377dff',
      '--contact-title': '#6c7275',
      '--contact-method': '#121212',
      '--contact-icon-bg': '#377dff',
      '--contact-icon-color': '#ffffff',

      // Orders History - Light Theme
      '--orders-bg': '#ffffff',
      '--orders-title': '#121212',
      '--orders-table-header': '#6c7275',
      '--orders-table-border': '#e2e8f0',
      '--orders-row-text': '#121212',
      '--orders-row-border': '#f1f5f9',
      '--orders-status-pending': '#f59e0b',
      '--orders-status-completed': '#10b981',
      '--orders-status-cancelled': '#ef4444',
      
      // Cart Page - Light Theme
      '--cart-bg': '#ffffff',
      '--cart-container-bg': 'linear-gradient(135deg, #f8fafc 0%, #ffffff 100%)',
      '--cart-title': '#1a1a1a',
      '--cart-title-underline': '#1a1a1a',
      '--cart-table-bg': '#ffffff',
      '--cart-table-header-bg': 'linear-gradient(135deg, #f8fafc 0%, #ffffff 100%)',
      '--cart-table-header-text': '#6b7280',
      '--cart-table-border': '#e5e7eb',
      '--cart-row-bg': '#ffffff',
      '--cart-row-hover': '#fafafa',
      '--cart-row-text': '#1a1a1a',
      '--cart-product-title': '#1a1a1a',
      '--cart-remove-btn': '#ef4444',
      '--cart-remove-btn-hover': '#dc2626',
      '--cart-remove-btn-bg-hover': '#fef2f2',
      '--cart-quantity-btn': '#1a1a1a',
      '--cart-quantity-btn-bg': '#ffffff',
      '--cart-quantity-btn-hover': '#ffffff',
      '--cart-quantity-btn-hover-text': '#1a1a1a',
      '--cart-quantity-number': '#1a1a1a',
      '--cart-price': '#6b7280',
      '--cart-subtotal': '#1a1a1a',
      '--cart-total-container-bg': '#ffffff',
      '--cart-total-title': '#1a1a1a',
      '--cart-total-price': '#1a1a1a',
      '--cart-checkout-btn': '#1a1a1a',
      '--cart-checkout-btn-text': '#ffffff',
      '--cart-empty-bg': '#ffffff',
      '--cart-empty-title': '#1a1a1a',
      '--cart-empty-text': '#6b7280',
      '--cart-error-bg': '#ffffff',
      '--cart-error-title': '#1a1a1a',
      '--cart-error-text': '#6b7280',
      '--cart-retry-btn': 'linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)',
      '--cart-retry-btn-text': '#ffffff',
      
      // Sign In & Sign Up Pages - Light Theme
      '--signin-bg': '#ffffff',
      '--signin-container-bg': '#ffffff',
      '--signin-form-bg': '#ffffff',
      '--signin-title': '#1e293b',
      '--signin-label': '#374151',
      '--signin-input-bg': '#ffffff',
      '--signin-input-border': '#d1d5db',
      '--signin-input-focus-border': '#3b82f6',
      '--signin-input-text': '#1e293b',
      '--signin-input-placeholder': '#9ca3af',
      '--signin-btn-bg': 'linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)',
      '--signin-btn-text': '#ffffff',
      '--signin-btn-hover': 'linear-gradient(135deg, #2563eb 0%, #1d4ed8 100%)',
      '--signin-btn-shadow': '0 4px 12px rgba(59, 130, 246, 0.3)',
      '--signin-link': '#3b82f6',
      '--signin-link-hover': '#2563eb',
      '--signin-error': '#ef4444',
      '--signin-text': '#6b7280',
      '--signin-checkbox': '#3b82f6',
      '--signin-remember-text': '#6b7280',
      '--signin-forgot-link': '#1e293b',
      '--signin-forgot-hover': '#3b82f6',
      '--signin-terms-text': '#6b7280',
      '--signin-terms-link': '#1e293b',
      '--signin-terms-hover': '#3b82f6',
      
      // Sign Up specific colors
      '--signup-profile-border': '#d1d5db',
      '--signup-profile-hover': '#3b82f6',
      '--signup-profile-text': '#6b7280',
      '--signup-bg': '#ffffff',
      '--signup-container-bg': '#ffffff',
      '--signup-form-bg': '#ffffff',
      '--signup-title': '#1e293b',
      '--signup-label': '#374151',
      '--signup-input-bg': '#ffffff',
      '--signup-input-border': '#d1d5db',
      '--signup-input-focus-border': '#3b82f6',
      '--signup-input-text': '#1e293b',
      '--signup-input-placeholder': '#9ca3af',
      '--signup-btn-bg': 'linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)',
      '--signup-btn-text': '#ffffff',
      '--signup-btn-hover': 'linear-gradient(135deg, #2563eb 0%, #1d4ed8 100%)',
      '--signup-btn-shadow': '0 4px 12px rgba(59, 130, 246, 0.3)',
      '--signup-link': '#3b82f6',
      '--signup-link-hover': '#2563eb',
      '--signup-error': '#ef4444',
      '--signup-text': '#6b7280',
      '--signup-checkbox': '#3b82f6',
      
      // Privacy Policy Page - Light Theme
      '--privacy-bg': 'linear-gradient(135deg, #f8f9fa 0%, #ffffff 100%)',
      '--privacy-container-bg': '#ffffff',
      '--privacy-header-border': '#e8e8e8',
      '--privacy-title': '#141718',
      '--privacy-subtitle': '#6c7275',
      '--privacy-intro': '#4a5568',
      '--privacy-section-title': '#141718',
      '--privacy-section-border': '#000000',
      '--privacy-section-border-accent': 'linear-gradient(90deg, #000000, #333333)',
      '--privacy-text': '#4a5568',
      '--privacy-bullet': '#000000',
      '--privacy-strong': '#141718',
      '--privacy-contact-bg': 'linear-gradient(135deg, #f8f9fa 0%, #ffffff 100%)',
      '--privacy-contact-border': '#000000',
      '--privacy-btn-bg': 'linear-gradient(135deg, #000000 0%, #333333 100%)',
      '--privacy-btn-text': '#ffffff',
      '--privacy-btn-hover-bg': 'linear-gradient(135deg, #333333 0%, #000000 100%)',
      '--privacy-btn-shadow': '0 4px 12px rgba(0, 0, 0, 0.15)',
      '--privacy-btn-shadow-hover': '0 6px 20px rgba(0, 0, 0, 0.25)',
      '--privacy-footer-note': '#6c7275',
      
      // Reset Password Page - Light Theme
      '--reset-bg': '#ffffff',
      '--reset-container-bg': '#ffffff',
      '--reset-form-bg': '#ffffff',
      '--reset-title': '#141718',
      '--reset-instructions': '#6c7275',
      '--reset-label': '#202525',
      '--reset-input-bg': '#ffffff',
      '--reset-input-border': '#ccc',
      '--reset-input-focus-border': '#141718',
      '--reset-input-text': '#141718',
      '--reset-input-placeholder': '#9ca3af',
      '--reset-btn-bg': 'linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)',
      '--reset-btn-text': '#ffffff',
      '--reset-btn-hover-bg': 'linear-gradient(135deg, #2563eb 0%, #1d4ed8 100%)',
      '--reset-btn-shadow': '0 4px 12px rgba(59, 130, 246, 0.3)',
      '--reset-btn-shadow-hover': '0 6px 20px rgba(59, 130, 246, 0.4)',
      '--reset-link': '#38cb89',
      '--reset-link-hover': '#059669',
      '--reset-text': '#6c7275',
      '--reset-error': '#ef4444',
      
      // Payment Pages - Light Theme
      '--payment-success-icon': '#22c55e',
      '--payment-success-bg': '#f0fdf4',
      '--payment-success-border': '#bbf7d0',
      '--payment-success-text': '#166534',
      '--payment-failure-icon': '#ef4444',
      '--payment-failure-bg': '#fef2f2',
      '--payment-failure-border': '#fecaca',
      '--payment-failure-text': '#b91c1c',
      
      // Review Section - Light Theme
      '--review-section-bg': '#ffffff',
      '--review-card-bg': '#ffffff',
      '--review-card-border': '#e2e8f0',
      '--review-card-shadow': '0 4px 20px rgba(0, 0, 0, 0.06)',
      '--review-card-hover-shadow': '0 12px 40px rgba(0, 0, 0, 0.12)',
      '--review-title': '#121212',
      '--review-text': '#6c7275',
      '--review-date': '#9ca3af',
      '--review-avatar-border': '#e2e8f0',
      '--review-star-filled': '#fbbf24',
      '--review-star-empty': '#e5e7eb',
      '--review-star-hover': '#f59e0b',
      '--review-form-bg': '#ffffff',
      '--review-form-border': '#e2e8f0',
      '--review-textarea-bg': '#ffffff',
      '--review-textarea-border': '#d1d5db',
      '--review-textarea-focus-border': '#377dff',
      '--review-submit-btn': 'linear-gradient(135deg, #377dff 0%, #2563eb 100%)',
      '--review-submit-btn-text': '#ffffff',
      '--review-submit-btn-hover': 'linear-gradient(135deg, #2563eb 0%, #1d4ed8 100%)',
      '--review-delete-icon': '#ef4444',
      '--review-delete-icon-hover': '#dc2626',
      
      // Product Details Counter - Light Theme
      '--counter-bg': '#f8fafc',
      '--counter-border': '#e2e8f0',
      '--counter-button-bg': '#377dff',
      '--counter-button-text': '#ffffff',
      '--counter-button-hover-bg': '#2563eb',
      '--counter-button-hover-text': '#ffffff',
      '--counter-button-disabled-bg': '#e5e7eb',
      '--counter-button-disabled-text': '#9ca3af',
      '--counter-value-bg': '#f8fafc',
      '--counter-value-text': '#121212',
    }
  },
  dark: {
    name: 'dark',
    colors: {
      '--bg': '#0f172a',
      '--text': '#f8fafc',
      '--text-gray': '#cbd5e1',
      '--text2': '#60a5fa',
      '--hover': '#e2e8f0',
      
      '--hero-bg': 'linear-gradient(135deg, #1e293b 0%, #0f172a 50%, #334155 100%)',
      '--hero-text': '#ffffff',
      '--hero-description': 'rgba(255, 255, 255, 0.85)',
      '--hero-btn-bg': 'linear-gradient(135deg, #60a5fa 0%, #3b82f6 100%)',
      '--hero-btn-text': '#ffffff',
      '--hero-btn-hover-bg': 'linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)',
      '--hero-btn-hover-text': '#ffffff',
      '--hero-btn-border': 'rgba(96, 165, 250, 0.3)',
      '--hero-overlay': 'rgba(0, 0, 0, 0.2)',
      
      '--navbar-bg': '#1e293b',
      '--navbar-border': '#334155',
      '--navbar-text': '#f1f5f9',
      '--navbar-text-hover': '#60a5fa',
      '--navbar-active': '#60a5fa',
      '--navbar-toggler': '#f1f5f9',
      '--navbar-toggler-border': '#475569',
      '--navbar-toggler-bg': '#60a5fa',
      '--navbar-toggler-hover-bg': '#334155',
      '--navbar-toggler-hover-border': '#60a5fa',
      '--navbar-link-hover-bg': 'rgba(96, 165, 250, 0.1)',
      '--navbar-link-active-bg': 'rgba(96, 165, 250, 0.15)',
      '--navbar-collapse-bg': '#1e293b',
      '--navbar-shadow': '0 2px 8px rgba(241, 245, 249, 0.1)',
      '--navbar-link-border': 'transparent',
      
      // Cards & Components
      '--card-bg': '#1e293b',
      '--card-border': '#334155',
      '--card-shadow': '0 0.1rem 0.2rem rgba(0, 0, 0, 0.3)',
      
      // Buttons
      '--btn-primary': '#3b82f6',
      '--btn-primary-hover': '#2563eb',
      '--btn-secondary': '#334155',
      '--btn-secondary-hover': '#475569',
      '--btn-text': '#ffffff',
      
      // Add to Cart Button - Dark Theme
      '--add-to-cart-bg': '#3b82f6',
      '--add-to-cart-hover-bg': '#2563eb',
      '--add-to-cart-text': '#ffffff',
      '--add-to-cart-shadow': '0 2px 4px rgba(59, 130, 246, 0.3)',
      '--add-to-cart-shadow-hover': '0 4px 8px rgba(59, 130, 246, 0.4)',
      
      '--input-bg': '#1e293b',
      '--input-border': '#475569',
      '--input-focus': '#3b82f6',
      '--input-text': '#f8fafc',
      
      // Counter & Badges
      '--counter-bg': '#334155',
      '--counter-text': '#f1f5f9',
      
      // Secondary Colors
      '--secondary-color': '#10b981',
      '--secondary-bg': '#1e293b',
      
      // Footer - Dark Theme
      '--footer-bg': '#0f172a',
      '--footer-text': '#cbd5e1',
      '--footer-link': '#60a5fa',
      '--footer-link-hover': '#93c5fd',
      '--footer-border': '#334155',
      '--footer-icon': '#94a3b8',
      '--footer-icon-hover': '#60a5fa',
      
      '--page-bg': '#0f172a',
      '--section-bg': '#1e293b',
      '--border-color': '#334155',
      '--text-muted': '#94a3b8',
      '--text-primary': '#f8fafc',
      '--text-secondary': '#cbd5e1',
      
      '--product-card-bg': '#1e293b',
      '--product-card-border': '#334155',
      '--product-card-shadow': '0 2px 8px rgba(0, 0, 0, 0.3)',
      '--product-card-shadow-hover': '0 8px 25px rgba(0, 0, 0, 0.4)',
      '--product-price': '#fbbf24',
      '--product-price-old': '#94a3b8',
      '--product-title': '#f1f5f9',
      '--product-description': '#cbd5e1',
      '--product-image-bg': '#0f172a',
      
      '--star-filled': '#ffffff',
      '--star-empty': '#000000',
      '--star-size': '16px',
      
      '--icon-color': '#cbd5e1',
      '--icon-bg': '#1e293b',
      '--icon-hover-bg': '#60a5fa',
      '--icon-hover-color': '#ffffff',
      '--icon-shadow': '0 2px 4px rgba(0, 0, 0, 0.3)',
      '--icon-shadow-hover': '0 4px 8px rgba(0, 0, 0, 0.4)',
      '--favorite-filled-color': '#f87171',
      '--favorite-hover-color': '#ef4444',
      
      '--badge-new-bg': '#059669',
      '--badge-discount-bg': '#dc2626',
      '--badge-text': '#ffffff',
      
      '--category-card-bg': '#1e293b',
      '--category-card-border': '#334155',
      '--category-title': '#f8fafc',
      '--category-text': '#cbd5e1',
      '--category-count': '#60a5fa',
      
      '--table-bg': '#1e293b',
      '--table-border': '#334155',
      '--table-header-bg': '#0f172a',
      '--table-row-hover': '#334155',
      
      '--bg-primary': '#1e293b',
      '--primary-600': '#60a5fa',
      
      // Modal
      '--modal-bg': '#1e293b',
      '--modal-close-bg': '#ef4444',
      '--modal-close-text': '#ffffff',
      '--modal-close-hover-bg': '#dc2626',

      '--indicator-bg': '#374151',
      '--indicator-active': '#60a5fa',
      '--indicator-hover': '#4b5563',

      // View More Button - Dark Theme
      '--view-more-btn-bg': '#60a5fa',
      '--view-more-btn-text': '#ffffff',
      '--view-more-btn-hover-bg': '#3b82f6',
      '--view-more-btn-hover-text': '#ffffff',
      '--view-more-btn-border': '#60a5fa',
      '--view-more-btn-shadow': '0 4px 12px rgba(96, 165, 250, 0.3)',
      '--view-more-btn-shadow-hover': '0 6px 16px rgba(96, 165, 250, 0.4)',

      // Category Products Page - Dark Theme
      '--category-page-bg': '#0f172a',
      '--category-title': '#f1f5f9',
      '--category-empty-bg': '#1e293b',
      '--category-empty-text': '#94a3b8',
      '--category-load-btn-bg': '#1e293b',
      '--category-load-btn-text': '#f1f5f9',
      '--category-load-btn-hover-bg': '#334155',
      '--category-load-btn-hover-text': '#ffffff',

      // Shop Page Hero - Dark Theme
      '--shop-hero-bg': 'linear-gradient(135deg, #1e293b 0%, #334155 100%)',
      '--shop-hero-text': '#f1f5f9',
      '--shop-hero-subtitle': '#cbd5e1',
      
      // Shop Form Elements - Dark Theme
      '--form-label': '#f1f5f9',
      '--form-input-bg': '#1e293b',
      '--form-input-border': '#475569',
      '--form-input-text': '#f1f5f9',
      '--form-input-placeholder': '#94a3b8',
      '--form-input-focus-border': '#60a5fa',
      '--form-input-focus-shadow': '0 0 0 3px rgba(96, 165, 250, 0.1)',

      // Contact Page - Dark Theme
      '--contact-info-bg': '#1e293b',
      '--contact-info-border': '#334155',
      '--contact-info-hover-bg': '#334155',
      '--contact-info-hover-border': '#60a5fa',
      '--contact-title': '#94a3b8',
      '--contact-method': '#f1f5f9',
      '--contact-icon-bg': '#60a5fa',
      '--contact-icon-color': '#ffffff',

      // Orders History - Dark Theme
      '--orders-bg': '#1e293b',
      '--orders-title': '#f1f5f9',
      '--orders-table-header': '#94a3b8',
      '--orders-table-border': '#334155',
      '--orders-row-text': '#f1f5f9',
      '--orders-row-border': '#334155',
      '--orders-status-pending': '#fbbf24',
      '--orders-status-completed': '#34d399',
      '--orders-status-cancelled': '#f87171',
      
      // Cart Page - Dark Theme
      '--cart-bg': '#1e293b',
      '--cart-container-bg': 'linear-gradient(135deg, #0f172a 0%, #1e293b 100%)',
      '--cart-title': '#f1f5f9',
      '--cart-title-underline': '#f1f5f9',
      '--cart-table-bg': '#334155',
      '--cart-table-header-bg': 'linear-gradient(135deg, #475569 0%, #334155 100%)',
      '--cart-table-header-text': '#94a3b8',
      '--cart-table-border': '#475569',
      '--cart-row-bg': '#334155',
      '--cart-row-hover': '#475569',
      '--cart-row-text': '#f1f5f9',
      '--cart-product-title': '#f1f5f9',
      '--cart-remove-btn': '#f87171',
      '--cart-remove-btn-hover': '#ef4444',
      '--cart-remove-btn-bg-hover': '#7f1d1d',
      '--cart-quantity-btn': '#f1f5f9',
      '--cart-quantity-btn-bg': '#475569',
      '--cart-quantity-btn-hover': '#f1f5f9',
      '--cart-quantity-btn-hover-text': '#1e293b',
      '--cart-quantity-number': '#f1f5f9',
      '--cart-price': '#94a3b8',
      '--cart-subtotal': '#f1f5f9',
      '--cart-total-container-bg': '#334155',
      '--cart-total-title': '#f1f5f9',
      '--cart-total-price': '#f1f5f9',
      '--cart-checkout-btn': '#f1f5f9',
      '--cart-checkout-btn-text': '#1e293b',
      '--cart-empty-bg': '#334155',
      '--cart-empty-title': '#f1f5f9',
      '--cart-empty-text': '#94a3b8',
      '--cart-error-bg': '#334155',
      '--cart-error-title': '#f1f5f9',
      '--cart-error-text': '#94a3b8',
      '--cart-retry-btn': 'linear-gradient(135deg, #0ea5e9 0%, #0284c7 100%)',
      '--cart-retry-btn-text': '#ffffff',
      
      // Payment Pages - Dark Theme
      '--payment-success-icon': '#34d399',
      '--payment-success-bg': '#064e3b',
      '--payment-success-border': '#065f46',
      '--payment-success-text': '#6ee7b7',
      '--payment-failure-icon': '#f87171',
      '--payment-failure-bg': '#7f1d1d',
      '--payment-failure-border': '#991b1b',
      '--payment-failure-text': '#fca5a5',
      
      // Review Section - Dark Theme
      '--review-section-bg': '#1e293b',
      '--review-card-bg': '#334155',
      '--review-card-border': '#475569',
      '--review-card-shadow': '0 4px 20px rgba(0, 0, 0, 0.3)',
      '--review-card-hover-shadow': '0 12px 40px rgba(0, 0, 0, 0.4)',
      '--review-title': '#f1f5f9',
      '--review-text': '#cbd5e1',
      '--review-date': '#94a3b8',
      '--review-avatar-border': '#475569',
      '--review-star-filled': '#fbbf24',
      '--review-star-empty': '#475569',
      '--review-star-hover': '#f59e0b',
      '--review-form-bg': '#334155',
      '--review-form-border': '#475569',
      '--review-textarea-bg': '#1e293b',
      '--review-textarea-border': '#475569',
      '--review-textarea-focus-border': '#60a5fa',
      '--review-submit-btn': 'linear-gradient(135deg, #60a5fa 0%, #3b82f6 100%)',
      '--review-submit-btn-text': '#ffffff',
      '--review-submit-btn-hover': 'linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)',
      '--review-delete-icon': '#ef4444',
      '--review-delete-icon-hover': '#dc2626',
      
      // Product Details Counter - Dark Theme
      '--counter-bg': '#334155',
      '--counter-border': '#475569',
      '--counter-button-bg': '#60a5fa',
      '--counter-button-text': '#ffffff',
      '--counter-button-hover-bg': '#3b82f6',
      '--counter-button-hover-text': '#ffffff',
      '--counter-button-disabled-bg': '#475569',
      '--counter-button-disabled-text': '#94a3b8',
      '--counter-value-bg': '#334155',
      '--counter-value-text': '#f1f5f9',
      
      // Sign In & Sign Up Pages - Dark Theme
      '--signin-bg': '#0f172a',
      '--signin-container-bg': '#1e293b',
      '--signin-form-bg': '#1e293b',
      '--signin-title': '#f1f5f9',
      '--signin-label': '#cbd5e1',
      '--signin-input-bg': '#334155',
      '--signin-input-border': '#475569',
      '--signin-input-focus-border': '#60a5fa',
      '--signin-input-text': '#f1f5f9',
      '--signin-input-placeholder': '#94a3b8',
      '--signin-btn-bg': 'linear-gradient(135deg, #0ea5e9 0%, #0284c7 100%)',
      '--signin-btn-text': '#ffffff',
      '--signin-btn-hover': 'linear-gradient(135deg, #0284c7 0%, #0369a1 100%)',
      '--signin-btn-shadow': '0 4px 12px rgba(14, 165, 233, 0.3)',
      '--signin-link': '#60a5fa',
      '--signin-link-hover': '#93c5fd',
      '--signin-error': '#f87171',
      '--signin-text': '#94a3b8',
      '--signin-checkbox': '#60a5fa',
      '--signin-remember-text': '#94a3b8',
      '--signin-forgot-link': '#f1f5f9',
      '--signin-forgot-hover': '#60a5fa',
      '--signin-terms-text': '#94a3b8',
      '--signin-terms-link': '#f1f5f9',
      '--signin-terms-hover': '#60a5fa',
      
      // Sign Up specific colors
      '--signup-profile-border': '#475569',
      '--signup-profile-hover': '#60a5fa',
      '--signup-profile-text': '#94a3b8',
      '--signup-bg': '#0f172a',
      '--signup-container-bg': '#1e293b',
      '--signup-form-bg': '#1e293b',
      '--signup-title': '#f1f5f9',
      '--signup-label': '#cbd5e1',
      '--signup-input-bg': '#334155',
      '--signup-input-border': '#475569',
      '--signup-input-focus-border': '#60a5fa',
      '--signup-input-text': '#f1f5f9',
      '--signup-input-placeholder': '#94a3b8',
      '--signup-btn-bg': 'linear-gradient(135deg, #0ea5e9 0%, #0284c7 100%)',
      '--signup-btn-text': '#ffffff',
      '--signup-btn-hover': 'linear-gradient(135deg, #0284c7 0%, #0369a1 100%)',
      '--signup-btn-shadow': '0 4px 12px rgba(14, 165, 233, 0.3)',
      '--signup-link': '#60a5fa',
      '--signup-link-hover': '#93c5fd',
      '--signup-error': '#f87171',
      '--signup-text': '#94a3b8',
      '--signup-checkbox': '#60a5fa',
      
      // Privacy Policy Page - Dark Theme
      '--privacy-bg': 'linear-gradient(135deg, #0f172a 0%, #1e293b 100%)',
      '--privacy-container-bg': '#1e293b',
      '--privacy-header-border': '#334155',
      '--privacy-title': '#f1f5f9',
      '--privacy-subtitle': '#94a3b8',
      '--privacy-intro': '#cbd5e1',
      '--privacy-section-title': '#f1f5f9',
      '--privacy-section-border': '#60a5fa',
      '--privacy-section-border-accent': 'linear-gradient(90deg, #60a5fa, #3b82f6)',
      '--privacy-text': '#cbd5e1',
      '--privacy-bullet': '#60a5fa',
      '--privacy-strong': '#f1f5f9',
      '--privacy-contact-bg': 'linear-gradient(135deg, #334155 0%, #1e293b 100%)',
      '--privacy-contact-border': '#60a5fa',
      '--privacy-btn-bg': 'linear-gradient(135deg, #0ea5e9 0%, #0284c7 100%)',
      '--privacy-btn-text': '#ffffff',
      '--privacy-btn-hover-bg': 'linear-gradient(135deg, #0284c7 0%, #0369a1 100%)',
      '--privacy-btn-shadow': '0 4px 12px rgba(14, 165, 233, 0.3)',
      '--privacy-btn-shadow-hover': '0 6px 20px rgba(14, 165, 233, 0.4)',
      '--privacy-footer-note': '#94a3b8',
      
      // Reset Password Page - Dark Theme
      '--reset-bg': '#0f172a',
      '--reset-container-bg': '#1e293b',
      '--reset-form-bg': '#1e293b',
      '--reset-title': '#f1f5f9',
      '--reset-instructions': '#94a3b8',
      '--reset-label': '#cbd5e1',
      '--reset-input-bg': '#334155',
      '--reset-input-border': '#475569',
      '--reset-input-focus-border': '#60a5fa',
      '--reset-input-text': '#f1f5f9',
      '--reset-input-placeholder': '#94a3b8',
      '--reset-btn-bg': 'linear-gradient(135deg, #0ea5e9 0%, #0284c7 100%)',
      '--reset-btn-text': '#ffffff',
      '--reset-btn-hover-bg': 'linear-gradient(135deg, #0284c7 0%, #0369a1 100%)',
      '--reset-btn-shadow': '0 4px 12px rgba(14, 165, 233, 0.3)',
      '--reset-btn-shadow-hover': '0 6px 20px rgba(14, 165, 233, 0.4)',
      '--reset-link': '#10b981',
      '--reset-link-hover': '#059669',
      '--reset-text': '#94a3b8',
      '--reset-error': '#f87171',
    }
  },
  beige: {
    name: 'beige',
    colors: {
      '--bg': '#F9F5F3',
      '--text': '#B2856E',
      '--text-gray': '#6B6765',
      '--text2': '#CD41C4',
      '--hover': '#6B6765',
      
      '--hero-bg': 'linear-gradient(135deg, #F9F5F3 0%, #E8D5C4 25%, #D4B08C 50%, #C19A7B 75%, #B2856E 100%)',
      '--hero-text': '#4A3C31',
      '--hero-description': '#6B4E3D',
      '--hero-btn-bg': 'linear-gradient(135deg, #CD41C4 0%, #B91C8B 100%)',
      '--hero-btn-text': '#F9F5F3',
      '--hero-btn-hover-bg': 'linear-gradient(135deg, #B91C8B 0%, #A61E7A 100%)',
      '--hero-btn-hover-text': '#F9F5F3',
      '--hero-overlay': 'rgba(205, 65, 196, 0.1)',
      
      // NavBar - Beige Theme
      '--navbar-bg': '#F9F5F3',
      '--navbar-border': '#DAD1CC',
      '--navbar-text': '#B2856E',
      '--navbar-text-hover': '#CD41C4',
      '--navbar-active': '#CD41C4',
      '--navbar-toggler': '#CD41C4',
      '--navbar-toggler-border': '#CD41C4',
      '--navbar-toggler-bg': '#F9F5F3',
      '--navbar-toggler-hover-bg': '#CD41C4',
      '--navbar-toggler-hover-border': '#B91C8B',
      '--navbar-link-hover-bg': 'rgba(205, 65, 196, 0.1)',
      '--navbar-link-active-bg': 'rgba(205, 65, 196, 0.15)',
      '--navbar-collapse-bg': '#F9F5F3',
      '--navbar-shadow': '0 2px 8px rgba(139, 69, 19, 0.1)',
      '--navbar-link-border': 'transparent',
      
      // Cards & Components
      '--card-bg': '#F9F5F3',
      '--card-border': '#DAD1CC',
      '--card-shadow': '0 0.1rem 0.2rem rgba(205, 65, 196, 0.1)',
      
      // Buttons
      '--btn-primary': '#CD41C4',
      '--btn-primary-hover': '#B91C8B',
      '--btn-secondary': '#DAD1CC',
      '--btn-secondary-hover': '#C5B8B0',
      '--btn-text': '#F9F5F3',
      
      // Add to Cart Button - Beige Theme
      '--add-to-cart-bg': '#CD41C4',
      '--add-to-cart-hover-bg': '#B91C8B',
      '--add-to-cart-text': '#F9F5F3',
      '--add-to-cart-shadow': '0 2px 4px rgba(205, 65, 196, 0.2)',
      '--add-to-cart-shadow-hover': '0 4px 8px rgba(205, 65, 196, 0.3)',
      
      // Forms & Inputs
      '--input-bg': '#F9F5F3',
      '--input-border': '#DAD1CC',
      '--input-focus': '#CD41C4',
      '--input-text': '#6B6765',
      
      // Counter & Badges
      '--counter-bg': '#CD41C4',
      '--counter-text': '#F9F5F3',
      
      // Secondary Colors
      '--secondary-color': '#B2856E',
      '--secondary-bg': '#F9F5F3',
      
      // Footer - Beige Theme
      '--footer-bg': '#F9F5F3',
      '--footer-text': '#6B6765',
      '--footer-link': '#CD41C4',
      '--footer-link-hover': '#B91C8B',
      '--footer-border': '#DAD1CC',
      '--footer-icon': '#6B6765',
      '--footer-icon-hover': '#CD41C4',
      
      // Cart & Account Pages
      '--page-bg': '#F9F5F3',
      '--section-bg': '#F9F5F3',
      '--border-color': '#DAD1CC',
      '--text-muted': '#6B6765',
      '--text-primary': '#B2856E',
      '--text-secondary': '#6B6765',
      
      '--product-card-bg': '#F9F5F3',
      '--product-card-border': '#DAD1CC',
      '--product-card-shadow': '0 2px 8px rgba(205, 65, 196, 0.1)',
      '--product-card-shadow-hover': '0 8px 25px rgba(205, 65, 196, 0.15)',
      '--product-price': '#CD41C4',
      '--product-price-old': '#6B6765',
      '--product-title': '#B2856E',
      '--product-description': '#6B6765',
      '--product-image-bg': '#F9F5F3',
      
      '--star-filled': '#CD41C4',
      '--star-empty': '#DAD1CC',
      '--star-empty-border': '#C5B8B0',
      '--star-size': '16px',
      
      '--icon-color': '#6B6765',
      '--icon-bg': '#F9F5F3',
      '--icon-hover-bg': '#CD41C4',
      '--icon-hover-color': '#F9F5F3',
      '--icon-shadow': '0 2px 4px rgba(205, 65, 196, 0.1)',
      '--icon-shadow-hover': '0 4px 8px rgba(205, 65, 196, 0.15)',
      '--favorite-filled-color': '#CD41C4',
      '--favorite-hover-color': '#B91C8B',
      
      '--badge-new-bg': '#38cb89',
      '--badge-discount-bg': '#ff6b6b',
      '--badge-text': '#ffffff',
      
      // Category Cards
      '--category-card-bg': '#F9F5F3',
      '--category-card-border': '#DAD1CC',
      '--category-title': '#B2856E',
      '--category-text': '#6B6765',
      '--category-count': '#CD41C4',
      
      // Category Products Page - Beige Theme
      '--category-page-bg': '#F9F5F3',
      '--category-empty-bg': '#DAD1CC',
      '--category-empty-text': '#6B6765',
      '--category-load-btn-bg': '#CD41C4',
      '--category-load-btn-text': '#F9F5F3',
      '--category-load-btn-hover-bg': '#B91C8B',
      '--category-load-btn-hover-text': '#F9F5F3',
      
      // Tables
      '--table-bg': '#F9F5F3',
      '--table-border': '#DAD1CC',
      '--table-header-bg': '#F9F5F3',
      '--table-row-hover': '#DAD1CC',
      
      // Design System Colors
      '--bg-primary': '#F9F5F3',
      '--primary-600': '#CD41C4',
      
      // Modal
      '--modal-bg': '#F9F5F3',
      '--modal-close-bg': '#CD41C4',
      '--modal-close-text': '#F9F5F3',
      '--modal-close-hover-bg': '#B91C8B',

      '--indicator-bg': '#DAD1CC',
      '--indicator-active': '#CD41C4',
      '--indicator-hover': '#C5B8B0',

      // View More Button - Beige Theme
      '--view-more-btn-bg': '#CD41C4',
      '--view-more-btn-text': '#F9F5F3',
      '--view-more-btn-hover-bg': '#B91C8B',
      '--view-more-btn-hover-text': '#F9F5F3',
      '--view-more-btn-border': '#CD41C4',
      '--view-more-btn-shadow': '0 4px 12px rgba(205, 65, 196, 0.3)',
      '--view-more-btn-shadow-hover': '0 6px 16px rgba(205, 65, 196, 0.4)',

      // Shop Page Hero - Beige Theme
      '--shop-hero-bg': 'linear-gradient(135deg, #6B6765 0%, #DAD1CC 33%, #B2856E 66%, #CD41C4 100%)',
      '--shop-hero-text': '#FFFFFF',
      '--shop-hero-subtitle': '#FFFFFF',
      
      // Shop Form Elements - Beige Theme
      '--form-label': '#B2856E',
      '--form-input-bg': '#F9F5F3',
      '--form-input-border': '#DAD1CC',
      '--form-input-text': '#6B6765',
      '--form-input-placeholder': '#6B6765',
      '--form-input-focus-border': '#CD41C4',
      '--form-input-focus-shadow': '0 0 0 3px rgba(205, 65, 196, 0.1)',

      // Contact Page - Beige Theme
      '--contact-info-bg': '#F9F5F3',
      '--contact-info-border': '#DAD1CC',
      '--contact-info-hover-bg': '#DAD1CC',
      '--contact-info-hover-border': '#CD41C4',
      '--contact-title': '#6B6765',
      '--contact-method': '#B2856E',
      '--contact-icon-bg': '#CD41C4',
      '--contact-icon-color': '#F9F5F3',

      // Orders History - Beige Theme
      '--orders-bg': '#F9F5F3',
      '--orders-title': '#B2856E',
      '--orders-table-header': '#6B6765',
      '--orders-table-border': '#DAD1CC',
      '--orders-row-text': '#B2856E',
      '--orders-row-border': '#DAD1CC',
      '--orders-status-pending': '#B2856E',
      '--orders-status-completed': '#CD41C4',
      '--orders-status-cancelled': '#6B6765',
      
      // Cart Page - Beige Theme
      '--cart-bg': '#F9F5F3',
      '--cart-container-bg': 'linear-gradient(135deg, #F9F5F3 0%, #F9F5F3 100%)',
      '--cart-title': '#B2856E',
      '--cart-title-underline': '#B2856E',
      '--cart-table-bg': '#F9F5F3',
      '--cart-table-header-bg': 'linear-gradient(135deg, #F9F5F3 0%, #F9F5F3 100%)',
      '--cart-table-header-text': '#6B6765',
      '--cart-table-border': '#DAD1CC',
      '--cart-row-bg': '#F9F5F3',
      '--cart-row-hover': '#DAD1CC',
      '--cart-row-text': '#B2856E',
      '--cart-product-title': '#B2856E',
      '--cart-remove-btn': '#CD41C4',
      '--cart-remove-btn-hover': '#B91C8B',
      '--cart-remove-btn-bg-hover': '#F9F5F3',
      '--cart-quantity-btn': '#CD41C4',
      '--cart-quantity-btn-bg': '#F9F5F3',
      '--cart-quantity-btn-hover': '#F9F5F3',
      '--cart-quantity-btn-hover-text': '#CD41C4',
      '--cart-quantity-number': '#B2856E',
      '--cart-price': '#6B6765',
      '--cart-subtotal': '#B2856E',
      '--cart-total-container-bg': '#F9F5F3',
      '--cart-total-title': '#B2856E',
      '--cart-total-price': '#B2856E',
      '--cart-checkout-btn': '#CD41C4',
      '--cart-checkout-btn-text': '#F9F5F3',
      '--cart-empty-bg': '#F9F5F3',
      '--cart-empty-title': '#B2856E',
      '--cart-empty-text': '#6B6765',
      '--cart-error-bg': '#F9F5F3',
      '--cart-error-title': '#B2856E',
      '--cart-error-text': '#6B6765',
      '--cart-retry-btn': 'linear-gradient(135deg, #CD41C4 0%, #B91C8B 100%)',
      '--cart-retry-btn-text': '#F9F5F3',
      
      // Payment Pages - Beige Theme
      '--payment-success-icon': '#CD41C4',
      '--payment-success-bg': '#F0F8F0',
      '--payment-success-border': '#C8E6C9',
      '--payment-success-text': '#2E7D32',
      '--payment-failure-icon': '#CD41C4',
      '--payment-failure-bg': '#FFEBEE',
      '--payment-failure-border': '#FFCDD2',
      '--payment-failure-text': '#C62828',
      
      // Review Section - Beige Theme
      '--review-section-bg': '#F9F5F3',
      '--review-card-bg': '#F9F5F3',
      '--review-card-border': '#DAD1CC',
      '--review-card-shadow': '0 4px 20px rgba(205, 65, 196, 0.1)',
      '--review-card-hover-shadow': '0 12px 40px rgba(205, 65, 196, 0.15)',
      '--review-title': '#8B4513',
      '--review-text': '#6B6765',
      '--review-date': '#A0522D',
      '--review-avatar-border': '#DAD1CC',
      '--review-star-filled': '#CD41C4',
      '--review-star-empty': '#DAD1CC',
      '--review-star-hover': '#B91C8B',
      '--review-form-bg': '#F9F5F3',
      '--review-form-border': '#DAD1CC',
      '--review-textarea-bg': '#F9F5F3',
      '--review-textarea-border': '#DAD1CC',
      '--review-textarea-focus-border': '#CD41C4',
      '--review-submit-btn': 'linear-gradient(135deg, #CD41C4 0%, #B91C8B 100%)',
      '--review-submit-btn-text': '#F9F5F3',
      '--review-submit-btn-hover': 'linear-gradient(135deg, #B91C8B 0%, #A61E7A 100%)',
      '--review-delete-icon': '#CD41C4',
      '--review-delete-icon-hover': '#B91C8B',
      
      // Product Details Counter - Beige Theme
      '--counter-bg': '#F9F5F3',
      '--counter-border': '#DAD1CC',
      '--counter-button-bg': '#CD41C4',
      '--counter-button-text': '#F9F5F3',
      '--counter-button-hover-bg': '#B91C8B',
      '--counter-button-hover-text': '#F9F5F3',
      '--counter-button-disabled-bg': '#DAD1CC',
      '--counter-button-disabled-text': '#6B6765',
      '--counter-value-bg': '#F9F5F3',
      '--counter-value-text': '#8B4513',
      
      // Sign In & Sign Up Pages - Beige Theme
      '--signin-bg': '#F9F5F3',
      '--signin-container-bg': '#F9F5F3',
      '--signin-form-bg': '#F9F5F3',
      '--signin-title': '#B2856E',
      '--signin-label': '#6B6765',
      '--signin-input-bg': '#F9F5F3',
      '--signin-input-border': '#DAD1CC',
      '--signin-input-focus-border': '#CD41C4',
      '--signin-input-text': '#6B6765',
      '--signin-input-placeholder': '#6B6765',
      '--signin-btn-bg': 'linear-gradient(135deg, #CD41C4 0%, #B91C8B 100%)',
      '--signin-btn-text': '#F9F5F3',
      '--signin-btn-hover': 'linear-gradient(135deg, #B91C8B 0%, #A61E7A 100%)',
      '--signin-btn-shadow': '0 4px 12px rgba(205, 65, 196, 0.3)',
      '--signin-link': '#CD41C4',
      '--signin-link-hover': '#B91C8B',
      '--signin-error': '#CD41C4',
      '--signin-text': '#6B6765',
      '--signin-checkbox': '#CD41C4',
      '--signin-remember-text': '#6B6765',
      '--signin-forgot-link': '#CD41C4',
      '--signin-forgot-hover': '#B91C8B',
      '--signin-terms-text': '#6B6765',
      '--signin-terms-link': '#CD41C4',
      '--signin-terms-hover': '#B91C8B',
      
      // Sign Up specific colors
      '--signup-profile-border': '#DAD1CC',
      '--signup-profile-hover': '#CD41C4',
      '--signup-profile-text': '#6B6765',
      '--signup-bg': '#F9F5F3',
      '--signup-container-bg': '#F9F5F3',
      '--signup-form-bg': '#F9F5F3',
      '--signup-title': '#B2856E',
      '--signup-label': '#6B6765',
      '--signup-input-bg': '#F9F5F3',
      '--signup-input-border': '#DAD1CC',
      '--signup-input-focus-border': '#CD41C4',
      '--signup-input-text': '#6B6765',
      '--signup-input-placeholder': '#6B6765',
      '--signup-btn-bg': 'linear-gradient(135deg, #CD41C4 0%, #B91C8B 100%)',
      '--signup-btn-text': '#F9F5F3',
      '--signup-btn-hover': 'linear-gradient(135deg, #B91C8B 0%, #A61E7A 100%)',
      '--signup-btn-shadow': '0 4px 12px rgba(205, 65, 196, 0.3)',
      '--signup-link': '#CD41C4',
      '--signup-link-hover': '#B91C8B',
      '--signup-error': '#CD41C4',
      '--signup-text': '#6B6765',
      '--signup-checkbox': '#CD41C4',
      
      // Privacy Policy Page - Beige Theme
      '--privacy-bg': 'linear-gradient(135deg, #F9F5F3 0%, #F9F5F3 100%)',
      '--privacy-container-bg': '#F9F5F3',
      '--privacy-header-border': '#DAD1CC',
      '--privacy-title': '#B2856E',
      '--privacy-subtitle': '#6B6765',
      '--privacy-intro': '#6B6765',
      '--privacy-section-title': '#B2856E',
      '--privacy-section-border': '#CD41C4',
      '--privacy-section-border-accent': 'linear-gradient(90deg, #CD41C4, #B91C8B)',
      '--privacy-text': '#6B6765',
      '--privacy-bullet': '#CD41C4',
      '--privacy-strong': '#B2856E',
      '--privacy-contact-bg': 'linear-gradient(135deg, #F9F5F3 0%, #F9F5F3 100%)',
      '--privacy-contact-border': '#CD41C4',
      '--privacy-btn-bg': 'linear-gradient(135deg, #CD41C4 0%, #B91C8B 100%)',
      '--privacy-btn-text': '#F9F5F3',
      '--privacy-btn-hover-bg': 'linear-gradient(135deg, #B91C8B 0%, #A61E7A 100%)',
      '--privacy-btn-shadow': '0 4px 12px rgba(205, 65, 196, 0.15)',
      '--privacy-btn-shadow-hover': '0 6px 20px rgba(205, 65, 196, 0.25)',
      '--privacy-footer-note': '#6B6765',
      
      // Reset Password Page - Beige Theme
      '--reset-bg': '#F9F5F3',
      '--reset-container-bg': '#F9F5F3',
      '--reset-form-bg': '#F9F5F3',
      '--reset-title': '#B2856E',
      '--reset-instructions': '#6B6765',
      '--reset-label': '#6B6765',
      '--reset-input-bg': '#F9F5F3',
      '--reset-input-border': '#DAD1CC',
      '--reset-input-focus-border': '#CD41C4',
      '--reset-input-text': '#6B6765',
      '--reset-input-placeholder': '#6B6765',
      '--reset-btn-bg': 'linear-gradient(135deg, #CD41C4 0%, #B91C8B 100%)',
      '--reset-btn-text': '#F9F5F3',
      '--reset-btn-hover-bg': 'linear-gradient(135deg, #B91C8B 0%, #A61E7A 100%)',
      '--reset-btn-shadow': '0 4px 12px rgba(205, 65, 196, 0.3)',
      '--reset-btn-shadow-hover': '0 6px 20px rgba(205, 65, 196, 0.4)',
      '--reset-link': '#CD41C4',
      '--reset-link-hover': '#B91C8B',
      '--reset-text': '#6B6765',
      '--reset-error': '#CD41C4',
    }
  }
};

export const applyTheme = (themeName) => {
  const theme = themes[themeName] || themes.light;
  const root = document.documentElement;
  
  Object.entries(theme.colors).forEach(([property, value]) => {
    root.style.setProperty(property, value);
  });
  
  console.log(`Theme applied: ${theme.name}`);
}; 